/*
 * This file is part of HearthStoneHelper.
 *
 * HearthStoneHelper is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * HearthStoneHelper is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with HearthStoneHelper.  If not, see <http://www.gnu.org/licenses/>.
 */
var arenaCards = [
	{ "id": "o05zlSi", "name": "preparation" },
	{ "id": "DhMiIil", "name": "ancestral-healing" },
	{ "id": "AZdB94j", "name": "totemic-might" },
	{ "id": "g1P1phP", "name": "wisp" },
	{ "id": "cDmFusM", "name": "inner-rage" },
	{ "id": "OHh0qhT", "name": "shadowstep" },
	{ "id": "XCegTXF", "name": "moonfire" },
	{ "id": "yD3iuRE", "name": "silence" },
	{ "id": "KYHCYjI", "name": "circle-of-healing" },
	{ "id": "pTN2IOu", "name": "target-dummy" },
	{ "id": "qlygJ6F", "name": "innervate" },
	{ "id": "TCLGMM6", "name": "sacrificial-pact" },
	{ "id": "g9ZCT5L", "name": "hunters-mark" },
	{ "id": "OAJWqKp", "name": "backstab" },
	{ "id": "ieCxJjn", "name": "eye-for-an-eye" },
	{ "id": "NguhUWt", "name": "hand-of-protection" },
	{ "id": "9ixOrKA", "name": "ice-lance" },
	{ "id": "HknODNl", "name": "frost-shock" },
	{ "id": "cQQewMW", "name": "cold-blood" },
	{ "id": "Uw5MrnB", "name": "power-overwhelming" },
	{ "id": "jK2S4ms", "name": "blessing-of-might" },
	{ "id": "NfKKaRi", "name": "northshire-cleric" },
	{ "id": "T5t7RCO", "name": "upgrade" },
	{ "id": "ylYUGMc", "name": "southsea-deckhand" },
	{ "id": "rkIhSFu", "name": "forked-lightning" },
	{ "id": "U68ltkh", "name": "clockwork-gnome" },
	{ "id": "yIbIEfb", "name": "abusive-sergeant" },
	{ "id": "N74nXAl", "name": "lightwarden" },
	{ "id": "5dZy0YI", "name": "lights-justice" },
	{ "id": "SYb6ocs", "name": "avenge" },
	{ "id": "bzK2N7g", "name": "earth-shock" },
	{ "id": "wi6afcP", "name": "arcane-shot" },
	{ "id": "Cc9GSKS", "name": "arcane-missiles" },
	{ "id": "5JWMp1f", "name": "secretkeeper" },
	{ "id": "RQDDxmG", "name": "dust-devil" },
	{ "id": "RqiJRPf", "name": "noble-sacrifice" },
	{ "id": "fJLMkMm", "name": "voodoo-doctor" },
	{ "id": "RKu30ox", "name": "young-priestess" },
	{ "id": "TaQpXja", "name": "young-dragonhawk" },
	{ "id": "Pwz01AG", "name": "sinister-strike" },
	{ "id": "BeZO6ek", "name": "inner-fire" },
	{ "id": "DfZeLmx", "name": "mind-vision" },
	{ "id": "LpckQ4b", "name": "repentance" },
	{ "id": "kKlT1RA", "name": "angry-chicken" },
	{ "id": "GDEPseG", "name": "warbot" },
	{ "id": "g43jmLP", "name": "shieldbearer" },
	{ "id": "xCtw1Ex", "name": "redemption" },
	{ "id": "5jr7h0b", "name": "execute" },
	{ "id": "h1GZUIM", "name": "whirlwind" },
	{ "id": "LjOwclT", "name": "blessing-of-wisdom" },
	{ "id": "2T0PBLY", "name": "shadowbomber" },
	{ "id": "fMWnrlO", "name": "grimscale-oracle" },
	{ "id": "Ou01HQr", "name": "timber-wolf" },
	{ "id": "SzwtJuq", "name": "mortal-coil" },
	{ "id": "lAhAnFR", "name": "mana-wyrm" },
	{ "id": "9DC5HQP", "name": "soulfire" },
	{ "id": "cepcxLW", "name": "flame-imp" },
	{ "id": "ApBoCqb", "name": "claw" },
	{ "id": "EIxi5W7", "name": "bestial-wrath" },
	{ "id": "3EccxRL", "name": "worgen-infiltrator" },
	{ "id": "plUeut8", "name": "shield-slam" },
	{ "id": "TtNgF7D", "name": "power-word-shield" },
	{ "id": "wCNNkwY", "name": "rockbiter-weapon" },
	{ "id": "yXKn2Bm", "name": "stonetusk-boar" },
	{ "id": "cA7KYWG", "name": "holy-smite" },
	{ "id": "Dg2Flse", "name": "elven-archer" },
	{ "id": "05gAezX", "name": "light-of-the-naaru" },
	{ "id": "wWpnC3N", "name": "webspinner" },
	{ "id": "8uuu5ud", "name": "zombie-chow" },
	{ "id": "6iZ25Wm", "name": "corruption" },
	{ "id": "k1RPZH7", "name": "naturalize" },
	{ "id": "mL5zhbc", "name": "deadly-poison" },
	{ "id": "IbrtK4C", "name": "voidwalker" },
	{ "id": "Tr0oHSh", "name": "bloodsail-corsair" },
	{ "id": "QbnXuZi", "name": "humility" },
	{ "id": "5ZA2GKb", "name": "tracking" },
	{ "id": "HtpbR5L", "name": "undertaker" },
	{ "id": "GMCGIWX", "name": "savagery" },
	{ "id": "xc4xOAF", "name": "argent-squire" },
	{ "id": "3xC5lyW", "name": "mirror-image" },
	{ "id": "CwuEHff", "name": "lightning-bolt" },
	{ "id": "w6f4m9E", "name": "goldshire-footman" },
	{ "id": "RxI40Yn", "name": "conceal" },
	{ "id": "jWU4UrI", "name": "murloc-tidecaller" },
	{ "id": "Nqgzxax", "name": "hungry-crab" },
	{ "id": "NtZA26r", "name": "murloc-raider" },
	{ "id": "l7AOfWI", "name": "blood-imp" },
	{ "id": "4D6yZBz", "name": "leper-gnome" },
	{ "id": "CJmttca", "name": "cogmaster" },
	{ "id": "RJlrlCo", "name": "ancient-watcher" },
	{ "id": "IQco0uJ", "name": "unstable-portal" },
	{ "id": "5EwLwsQ", "name": "cruel-taskmaster" },
	{ "id": "jyOZwSf", "name": "recombobulator" },
	{ "id": "gRSnWD6", "name": "feign-death" },
	{ "id": "E8gkDoX", "name": "ancestral-spirit" },
	{ "id": "yqlaDJo", "name": "lightwell" },
	{ "id": "7NWearx", "name": "seal-of-light" },
	{ "id": "JcFjocH", "name": "freezing-trap" },
	{ "id": "DWdlKfi", "name": "echoing-ooze" },
	{ "id": "Wqwaz0Z", "name": "eviscerate" },
	{ "id": "si29ATu", "name": "blade-flurry" },
	{ "id": "7PAzpNT", "name": "call-pet" },
	{ "id": "0JaJqMc", "name": "annoy-o-tron" },
	{ "id": "hTDRms7", "name": "commanding-shout" },
	{ "id": "2kaQj6U", "name": "holy-light" },
	{ "id": "efurx0z", "name": "goblin-auto-barber" },
	{ "id": "S01eP9t", "name": "frostbolt" },
	{ "id": "xTLTdsR", "name": "pint-sized-summoner" },
	{ "id": "IUAIgJi", "name": "nerubar-weblord" },
	{ "id": "6KTE4CL", "name": "novice-engineer" },
	{ "id": "yqdjJMp", "name": "sorcerers-apprentice" },
	{ "id": "cX2PR4S", "name": "youthful-brewmaster" },
	{ "id": "5Y6fXRB", "name": "micro-machine" },
	{ "id": "rzOPM10", "name": "mind-blast" },
	{ "id": "efCxQ26", "name": "dire-wolf-alpha" },
	{ "id": "ialzKZG", "name": "demonfire" },
	{ "id": "EhWhDNA", "name": "wrath" },
	{ "id": "U7pxKmH", "name": "loot-hoarder" },
	{ "id": "PEdEpKN", "name": "battle-rage" },
	{ "id": "xHNaSiY", "name": "shielded-minibot" },
	{ "id": "4OKtIxD", "name": "sunfury-protector" },
	{ "id": "ItUDU6f", "name": "shadowboxer" },
	{ "id": "4nE2q0W", "name": "darkbomb" },
	{ "id": "x7kIMw2", "name": "shadow-word-pain" },
	{ "id": "5ty510u", "name": "doomsayer" },
	{ "id": "gWMa7Ge", "name": "mechwarper" },
	{ "id": "YJlYZ9s", "name": "shiv" },
	{ "id": "tATcGch", "name": "snake-trap" },
	{ "id": "W6l40e0", "name": "mana-wraith" },
	{ "id": "H3stDec", "name": "vitality-totem" },
	{ "id": "TQMDOLu", "name": "gilblin-stalker" },
	{ "id": "K00ltpn", "name": "river-crocolisk" },
	{ "id": "R6aMqbE", "name": "puddlestomper" },
	{ "id": "wEhIWqA", "name": "lorewalker-cho" },
	{ "id": "Qfz6DDs", "name": "flametongue-totem" },
	{ "id": "uItYbeA", "name": "fiery-war-axe" },
	{ "id": "ta26yiI", "name": "flamecannon" },
	{ "id": "FG94E97", "name": "steamwheedle-sniper" },
	{ "id": "oTJkFWC", "name": "flare" },
	{ "id": "zZuBS8T", "name": "explosive-trap" },
	{ "id": "CYP119M", "name": "rampage" },
	{ "id": "zPx7h3T", "name": "wild-pyromancer" },
	{ "id": "jmrsE0F", "name": "kobold-geomancer" },
	{ "id": "X3IwL8p", "name": "snipe" },
	{ "id": "BeofopR", "name": "one-eyed-cheat" },
	{ "id": "XxpxpkH", "name": "slam" },
	{ "id": "yWDYGZr", "name": "equality" },
	{ "id": "kB5riOG", "name": "anodized-robo-cub" },
	{ "id": "sGK1DW8", "name": "mad-bomber" },
	{ "id": "9LpI0bs", "name": "crazed-alchemist" },
	{ "id": "Z3EjURk", "name": "mad-scientist" },
	{ "id": "JPUwtJr", "name": "mistress-of-pain" },
	{ "id": "PlhwEuX", "name": "stonesplinter-trogg" },
	{ "id": "4k3d8GQ", "name": "snowchugger" },
	{ "id": "JTwspQG", "name": "divine-spirit" },
	{ "id": "5p1ciKE", "name": "millhouse-manastorm" },
	{ "id": "Xyg3kPk", "name": "faerie-dragon" },
	{ "id": "5PeFtEQ", "name": "nat-pagle" },
	{ "id": "8cw3fgy", "name": "shrinkmeister" },
	{ "id": "bWhTwcI", "name": "patient-assassin" },
	{ "id": "xwNlwuZ", "name": "betrayal" },
	{ "id": "DDNDCRi", "name": "whirling-zap-o-matic" },
	{ "id": "0Oqz9b3", "name": "explosive-sheep" },
	{ "id": "U2ZQWPs", "name": "ships-cannon" },
	{ "id": "fj20Sfs", "name": "captains-parrot" },
	{ "id": "kRQXEcQ", "name": "heroic-strike" },
	{ "id": "0ibKApG", "name": "bluegill-warrior" },
	{ "id": "mAbwTrb", "name": "nerubian-egg" },
	{ "id": "mu5fak0", "name": "bloodsail-raider" },
	{ "id": "TXSMHq3", "name": "bloodfen-raptor" },
	{ "id": "4qCjzfG", "name": "bloodmage-thalnos" },
	{ "id": "ZBoZuzR", "name": "misdirection" },
	{ "id": "nxodFP2", "name": "unstable-ghoul" },
	{ "id": "C25BfLX", "name": "reincarnate" },
	{ "id": "sR6f37c", "name": "crackle" },
	{ "id": "pZJXuUf", "name": "defias-ringleader" },
	{ "id": "yTmJU3G", "name": "acidic-swamp-ooze" },
	{ "id": "PEdnxwH", "name": "glaivezooka" },
	{ "id": "gDZ8wks", "name": "power-of-the-wild" },
	{ "id": "1NzHFA5", "name": "mark-of-the-wild" },
	{ "id": "a3QSW9t", "name": "wild-growth" },
	{ "id": "HLRgJ24", "name": "ironbeak-owl" },
	{ "id": "bnJYcG0", "name": "argent-protector" },
	{ "id": "SSkuKa0", "name": "master-swordsmith" },
	{ "id": "Y2aINtn", "name": "armorsmith" },
	{ "id": "3HiYOjm", "name": "sap" },
	{ "id": "96TxjqW", "name": "amani-berserker" },
	{ "id": "Sh2e0xH", "name": "stormforged-axe" },
	{ "id": "EBqqM3q", "name": "frostwolf-grunt" },
	{ "id": "ujMRWz0", "name": "cleave" },
	{ "id": "TRRqUZ0", "name": "windfury" },
	{ "id": "UnO6chG", "name": "knife-juggler" },
	{ "id": "pgJMCHp", "name": "scavenging-hyena" },
	{ "id": "0iBZDWj", "name": "haunted-creeper" },
	{ "id": "Re3Fucn", "name": "succubus" },
	{ "id": "gOaxE80", "name": "arcane-explosion" },
	{ "id": "ufoT7nH", "name": "mana-addict" },
	{ "id": "AGMx4Gl", "name": "murloc-tidehunter" },
	{ "id": "Gm8gxml", "name": "jungle-panther" },
	{ "id": "3GGTb4M", "name": "questing-adventurer" },
	{ "id": "hxteagi", "name": "muster-for-battle" },
	{ "id": "ZiBhRZ4", "name": "gnomish-experimenter" },
	{ "id": "B3c1T2Y", "name": "sword-of-justice" },
	{ "id": "UwBNkgk", "name": "unleash-the-hounds" },
	{ "id": "XDukU9H", "name": "si7-agent" },
	{ "id": "qR1mhum", "name": "frost-nova" },
	{ "id": "hDJbQ2b", "name": "charge" },
	{ "id": "o38sXwr", "name": "fan-of-knives" },
	{ "id": "z0Jqn1o", "name": "razorfen-hunter" },
	{ "id": "0QobEmO", "name": "powermace" },
	{ "id": "xKamMt0", "name": "animal-companion" },
	{ "id": "e00eI9Z", "name": "southsea-captain" },
	{ "id": "TH9j5AE", "name": "drain-life" },
	{ "id": "Cl0bIsD", "name": "raid-leader" },
	{ "id": "l4FqRO0", "name": "goblin-sapper" },
	{ "id": "J4cHLEF", "name": "duplicate" },
	{ "id": "wAM5IYl", "name": "earthen-ring-farseer" },
	{ "id": "P8dp4G3", "name": "hobgoblin" },
	{ "id": "fhKIwyQ", "name": "aldor-peacekeeper" },
	{ "id": "6sJynyM", "name": "arcane-golem" },
	{ "id": "gd3juh1", "name": "arcane-intellect" },
	{ "id": "kwB46js", "name": "hex" },
	{ "id": "kIPttrS", "name": "coldlight-seer" },
	{ "id": "XXpIePK", "name": "coldlight-oracle" },
	{ "id": "dEQaI19", "name": "ice-block" },
	{ "id": "nFO0PzD", "name": "ice-barrier" },
	{ "id": "PM35wGY", "name": "lil-exorcist" },
	{ "id": "T8IciBE", "name": "imp-master" },
	{ "id": "Q2eOLXw", "name": "magma-rager" },
	{ "id": "7QB750T", "name": "stoneskin-gargoyle" },
	{ "id": "89EhK9O", "name": "tinkmaster-overspark" },
	{ "id": "K3iGerA", "name": "tinkertown-technician" },
	{ "id": "LZeWCqb", "name": "emperor-cobra" },
	{ "id": "l0Eoik4", "name": "bouncing-blade" },
	{ "id": "IlL25en", "name": "thoughtsteal" },
	{ "id": "XqRoISA", "name": "felguard" },
	{ "id": "PQdYXlL", "name": "sense-demons" },
	{ "id": "eKhZ6YM", "name": "warsong-commander" },
	{ "id": "o2mDq08", "name": "spellbender" },
	{ "id": "tCjzBUu", "name": "alarm-o-bot" },
	{ "id": "ktkTqPR", "name": "demolisher" },
	{ "id": "pKemMa9", "name": "unbound-elemental" },
	{ "id": "MZaCzab", "name": "illuminator" },
	{ "id": "OZU77TS", "name": "shadowform" },
	{ "id": "1rOy9gg", "name": "shadow-bolt" },
	{ "id": "gDZlIUl", "name": "shadow-word-death" },
	{ "id": "hJhE8kx", "name": "frothing-berserker" },
	{ "id": "PJbHaoY", "name": "raging-worgen" },
	{ "id": "HEHak8S", "name": "kill-command" },
	{ "id": "lX7M8q9", "name": "grove-tender" },
	{ "id": "2QMza3A", "name": "deathlord" },
	{ "id": "bOMbZCX", "name": "perditions-blade" },
	{ "id": "Z53NHUF", "name": "healing-touch" },
	{ "id": "lGpRri9", "name": "mana-tide-totem" },
	{ "id": "ltsdC1g", "name": "counterspell" },
	{ "id": "iODFHst", "name": "soot-spewer" },
	{ "id": "mNTJIuU", "name": "lava-burst" },
	{ "id": "urQhS3r", "name": "tauren-warrior" },
	{ "id": "EmgMItP", "name": "wolfrider" },
	{ "id": "wXxM5ha", "name": "big-game-hunter" },
	{ "id": "YGz5HBG", "name": "shield-block" },
	{ "id": "pbel0R6", "name": "shattered-sun-cleric" },
	{ "id": "bOOLY85", "name": "divine-favor" },
	{ "id": "eUPOTuQ", "name": "king-mukla" },
	{ "id": "JzpLHXa", "name": "mind-control-tech" },
	{ "id": "A0m3Mqf", "name": "shade-of-naxxramas" },
	{ "id": "jo3qaFq", "name": "velens-chosen" },
	{ "id": "xEnyse8", "name": "kirin-tor-mage" },
	{ "id": "yqG9aru", "name": "flesheating-ghoul" },
	{ "id": "HUAfIB1", "name": "mark-of-nature" },
	{ "id": "IPRHXZ7", "name": "deadly-shot" },
	{ "id": "dIwEzJy", "name": "dancing-swords" },
	{ "id": "4btwTzC", "name": "edwin-vancleef" },
	{ "id": "CjKYIsu", "name": "acolyte-of-pain" },
	{ "id": "HBnfi32", "name": "thrallmar-farseer" },
	{ "id": "wfrL6y3", "name": "vaporize" },
	{ "id": "k3xNm04", "name": "void-terror" },
	{ "id": "1BKdUYg", "name": "spider-tank" },
	{ "id": "SLDynwt", "name": "scarlet-purifier" },
	{ "id": "9FngXqi", "name": "scarlet-crusader" },
	{ "id": "z5g8Tro", "name": "blood-knight" },
	{ "id": "1K31c7I", "name": "headcrack" },
	{ "id": "dqiQKKY", "name": "far-sight" },
	{ "id": "5kj30GG", "name": "gnomeregan-infantry" },
	{ "id": "FLlkLGx", "name": "injured-blademaster" },
	{ "id": "JgNm2j5", "name": "dalaran-mage" },
	{ "id": "p5fHLYK", "name": "feral-spirit" },
	{ "id": "qt4LKit", "name": "savage-roar" },
	{ "id": "R9LIAlM", "name": "metaltooth-leaper" },
	{ "id": "G89Ldu4", "name": "iron-sensei" },
	{ "id": "bNL1N5c", "name": "ironforge-rifleman" },
	{ "id": "J2EKLk8", "name": "ironfur-grizzly" },
	{ "id": "T2d3i05", "name": "silverback-patriarch" },
	{ "id": "PL8HCs6", "name": "mirror-entity" },
	{ "id": "OWAXNsB", "name": "lightning-storm" },
	{ "id": "E9G7e4q", "name": "flying-machine" },
	{ "id": "MkEYb8d", "name": "ogre-warmaul" },
	{ "id": "i54psnu", "name": "ogre-brute" },
	{ "id": "ISuI1tS", "name": "murloc-warleader" },
	{ "id": "DKInzyB", "name": "eaglehorn-bow" },
	{ "id": "NOFpNUF", "name": "harvest-golem" },
	{ "id": "YBSgHJe", "name": "dark-cultist" },
	{ "id": "Uh26q1N", "name": "coghammer" },
	{ "id": "4ZyROj2", "name": "cogmasters-wrench" },
	{ "id": "Cl0NJjt", "name": "soul-of-the-forest" },
	{ "id": "NgEhlFf", "name": "keeper-of-the-grove" },
	{ "id": "zKErqSS", "name": "master-of-disguise" },
	{ "id": "qYsNlaP", "name": "gnomish-inventor" },
	{ "id": "heURUFd", "name": "tinkers-sharpsword-oil" },
	{ "id": "P16g5lm", "name": "ancestors-call" },
	{ "id": "RomlyrN", "name": "lightspawn" },
	{ "id": "tPL79Bd", "name": "cone-of-cold" },
	{ "id": "1a9tJoW", "name": "chillwind-yeti" },
	{ "id": "wczOw5W", "name": "poison-seeds" },
	{ "id": "AXwNgsL", "name": "polymorph" },
	{ "id": "QHA6o7Z", "name": "summoning-portal" },
	{ "id": "fgZZOZ1", "name": "wailing-soul" },
	{ "id": "AiJ7dqo", "name": "hellfire" },
	{ "id": "Wn1dFKA", "name": "goblin-blastmage" },
	{ "id": "7PxNsBn", "name": "jeeves" },
	{ "id": "Dn1yd3x", "name": "multi-shot" },
	{ "id": "tzfJw5L", "name": "consecration" },
	{ "id": "7cDTbY5", "name": "auchenai-soulpriest" },
	{ "id": "foNbXzr", "name": "wee-spellstopper" },
	{ "id": "qp86Kwt", "name": "mini-mage" },
	{ "id": "Wplq55p", "name": "imp-losion" },
	{ "id": "L3xkohE", "name": "ancient-mage" },
	{ "id": "9lfTraB", "name": "ancient-brewmaster" },
	{ "id": "3WGTDCU", "name": "korkron-elite" },
	{ "id": "kj8QNDx", "name": "screwjank-clunker" },
	{ "id": "mHShwPn", "name": "enhance-o-mechano" },
	{ "id": "2kKhRBC", "name": "dread-corsair" },
	{ "id": "Z0LDkZD", "name": "hammer-of-wrath" },
	{ "id": "beSHblC", "name": "mindgames" },
	{ "id": "DU1slqj", "name": "bite" },
	{ "id": "eYjJtjE", "name": "arcane-nullifier-x-21" },
	{ "id": "jZJ0tNd", "name": "sabotage" },
	{ "id": "wCinLdR", "name": "shadowflame" },
	{ "id": "EyTokp4", "name": "shadow-madness" },
	{ "id": "FSN1trP", "name": "twilight-drake" },
	{ "id": "wf8pLjT", "name": "stormwind-knight" },
	{ "id": "lMdKRK4", "name": "dragonling-mechanic" },
	{ "id": "Byl5eY2", "name": "mechanical-yeti" },
	{ "id": "XrsLUf3", "name": "senjin-shieldmasta" },
	{ "id": "qXu5Chw", "name": "swipe" },
	{ "id": "9nyWJH5", "name": "deaths-bite" },
	{ "id": "2mXnGU3", "name": "water-elemental" },
	{ "id": "mtncaCe", "name": "siltfin-spiritwalker" },
	{ "id": "MZ2RQIc", "name": "pit-lord" },
	{ "id": "eneAHRB", "name": "fireball" },
	{ "id": "PMBlGQt", "name": "blessing-of-kings" },
	{ "id": "jsqOLs8", "name": "baron-rivendare" },
	{ "id": "ZxYxoXx", "name": "truesilver-champion" },
	{ "id": "4AkMxlo", "name": "burly-rockjaw-trogg" },
	{ "id": "tuEuSaT", "name": "dunemaul-shaman" },
	{ "id": "Odaligh", "name": "spellbreaker" },
	{ "id": "EQL6IaR", "name": "kezan-mystic" },
	{ "id": "EyPJEEz", "name": "voidcaller" },
	{ "id": "MoEuKD0", "name": "violet-teacher" },
	{ "id": "rliFXYx", "name": "oasis-snapjaw" },
	{ "id": "bEkLe9L", "name": "mass-dispel" },
	{ "id": "hwnRQFi", "name": "old-murk-eye" },
	{ "id": "cwtnUf4", "name": "mortal-strike" },
	{ "id": "oLszYm0", "name": "ethereal-arcanist" },
	{ "id": "30tSnRl", "name": "cult-master" },
	{ "id": "cZu18X9", "name": "piloted-shredder" },
	{ "id": "531Le87", "name": "lost-tallstrider" },
	{ "id": "YZUjW4x", "name": "fel-cannon" },
	{ "id": "wChUi23", "name": "silvermoon-guardian" },
	{ "id": "rtFhm9q", "name": "anubar-ambusher" },
	{ "id": "Px578km", "name": "defender-of-argus" },
	{ "id": "T6Nh7b5", "name": "arathi-weaponsmith" },
	{ "id": "9Lt1sTC", "name": "windspeaker" },
	{ "id": "XpApXQA", "name": "ogre-magi" },
	{ "id": "zachCQB", "name": "houndmaster" },
	{ "id": "BKPQRu8", "name": "mogushan-warden" },
	{ "id": "XRUhRNe", "name": "echo-of-medivh" },
	{ "id": "4QIGQHL", "name": "dark-iron-dwarf" },
	{ "id": "PsmBAfx", "name": "bolvar-fordragon" },
	{ "id": "5ta124A", "name": "quartermaster" },
	{ "id": "Ic3WTeu", "name": "druid-of-the-claw" },
	{ "id": "3IfU2YO", "name": "assassins-blade" },
	{ "id": "hR3NiYO", "name": "assassinate" },
	{ "id": "ImYAj5e", "name": "blessed-champion" },
	{ "id": "7LSlyzz", "name": "gurubashi-berserker" },
	{ "id": "Mb4L96t", "name": "harrison-jones" },
	{ "id": "97De9i8", "name": "bloodlust" },
	{ "id": "lngWhps", "name": "junkbot" },
	{ "id": "Xn6GA4W", "name": "earth-elemental" },
	{ "id": "wH6x9yk", "name": "nightblade" },
	{ "id": "y7qsz28", "name": "arcanite-reaper" },
	{ "id": "DfysUOS", "name": "druid-of-the-fang" },
	{ "id": "w2ZZR91", "name": "blingtron-3000" },
	{ "id": "d1SBkO4", "name": "spiteful-smith" },
	{ "id": "mrEgG99", "name": "demonheart" },
	{ "id": "5KqDuXa", "name": "abomination" },
	{ "id": "THab0Dk", "name": "stalagg" },
	{ "id": "2umbWQT", "name": "faceless-manipulator" },
	{ "id": "XpzobTP", "name": "starfall" },
	{ "id": "u2yF1hI", "name": "darkscale-healer" },
	{ "id": "ao0mH4R", "name": "doomguard" },
	{ "id": "XkYqZaQ", "name": "bane-of-doom" },
	{ "id": "j8Uw2qM", "name": "bomb-lobber" },
	{ "id": "pXLYhrc", "name": "doomhammer" },
	{ "id": "WNZ63Rm", "name": "voljin" },
	{ "id": "CuFQyds", "name": "fen-creeper" },
	{ "id": "9CczKox", "name": "loatheb" },
	{ "id": "auiJplh", "name": "sludge-belcher" },
	{ "id": "8YGqnXP", "name": "nourish" },
	{ "id": "K6DMUYE", "name": "floating-watcher" },
	{ "id": "owrKDje", "name": "leeroy-jenkins" },
	{ "id": "C1yWm2g", "name": "salty-dog" },
	{ "id": "u4PQ64h", "name": "explosive-shot" },
	{ "id": "FCIbi3O", "name": "stampeding-kodo" },
	{ "id": "PNeK3Cq", "name": "madder-bomber" },
	{ "id": "MyjZhsA", "name": "silver-hand-knight" },
	{ "id": "drQOxrJ", "name": "king-of-beasts" },
	{ "id": "hhuWudI", "name": "cobra-shot" },
	{ "id": "XPLuCyQ", "name": "azure-drake" },
	{ "id": "1W3ZaBC", "name": "holy-wrath" },
	{ "id": "fDtBF3o", "name": "holy-nova" },
	{ "id": "JEZWbI4", "name": "mimirons-head" },
	{ "id": "k1Ib9ft", "name": "elite-tauren-chieftain" },
	{ "id": "dZNM88b", "name": "brawl" },
	{ "id": "Gk2mS5X", "name": "captain-greenskin" },
	{ "id": "NmSXiNd", "name": "antique-healbot" },
	{ "id": "aiW7H6l", "name": "tundra-rhino" },
	{ "id": "LfFinXh", "name": "stranglethorn-tiger" },
	{ "id": "zhF4kl3", "name": "booty-bay-bodyguard" },
	{ "id": "8mQu86J", "name": "feugen" },
	{ "id": "b9PyGzi", "name": "hemet-nesingwary" },
	{ "id": "5oxQlw2", "name": "siege-engine" },
	{ "id": "byGy6ky", "name": "cobalt-guardian" },
	{ "id": "swt2PYh", "name": "stormpike-commando" },
	{ "id": "isl69MG", "name": "frostwolf-warlord" },
	{ "id": "6KqoLSW", "name": "venture-co-mercenary" },
	{ "id": "rIyWH4T", "name": "ogre-ninja" },
	{ "id": "zQFjU14", "name": "starving-buzzard" },
	{ "id": "z89cXJB", "name": "upgraded-repair-bot" },
	{ "id": "zhm82NH", "name": "spectral-knight" },
	{ "id": "w7jm2pN", "name": "fel-reaver" },
	{ "id": "zLfaXUj", "name": "illidan-stormrage" },
	{ "id": "3wHrU72", "name": "frost-elemental" },
	{ "id": "AOUlFO4", "name": "cairne-bloodhoof" },
	{ "id": "yOPwjhK", "name": "gazlowe" },
	{ "id": "b0cHPtf", "name": "gadgetzan-auctioneer" },
	{ "id": "BlswbRe", "name": "trade-prince-gallywix" },
	{ "id": "buZnlSa", "name": "kidnapper" },
	{ "id": "5iCChCd", "name": "recycle" },
	{ "id": "Kiswxjz", "name": "lightbomb" },
	{ "id": "y0S8Tl8", "name": "temple-enforcer" },
	{ "id": "TltlDwF", "name": "avenging-wrath" },
	{ "id": "j06crAp", "name": "archmage" },
	{ "id": "B8hn40b", "name": "sylvanas-windrunner" },
	{ "id": "T891ftN", "name": "anima-golem" },
	{ "id": "bafsoG0", "name": "dread-infernal" },
	{ "id": "C0jct9Z", "name": "toshley" },
	{ "id": "ogGWTIn", "name": "starfire" },
	{ "id": "UM9TXmq", "name": "blizzard" },
	{ "id": "Wla7N6p", "name": "mech-bear-cat" },
	{ "id": "5NWx7Rk", "name": "gelbin-mekkatorque" },
	{ "id": "5gUp3UI", "name": "the-beast" },
	{ "id": "q17YJfp", "name": "vanish" },
	{ "id": "O9PRGFk", "name": "fire-elemental" },
	{ "id": "MWnfpHB", "name": "siphon-soul" },
	{ "id": "x096LlP", "name": "sunwalker" },
	{ "id": "hwFswpp", "name": "shieldmaiden" },
	{ "id": "rPL7ef6", "name": "boulderfist-ogre" },
	{ "id": "hDuAItS", "name": "holy-fire" },
	{ "id": "CfZ1JNA", "name": "cabal-shadow-priest" },
	{ "id": "sQdPyPT", "name": "lord-of-the-arena" },
	{ "id": "Yk30xu7", "name": "force-of-nature" },
	{ "id": "jWz9J7j", "name": "priestess-of-elune" },
	{ "id": "Ouyy71X", "name": "piloted-sky-golem" },
	{ "id": "FrbtTTB", "name": "maexxna" },
	{ "id": "6H3JpD3", "name": "iron-juggernaut" },
	{ "id": "Ww8gNOX", "name": "argent-commander" },
	{ "id": "Eu6jX6R", "name": "savannah-highmane" },
	{ "id": "kckP3Qn", "name": "hogger" },
	{ "id": "cz8pzDZ", "name": "windfury-harpy" },
	{ "id": "ynhHLXx", "name": "mogor-the-ogre" },
	{ "id": "9y48IqF", "name": "reckless-rocketeer" },
	{ "id": "FOS8ixB", "name": "dark-wispers" },
	{ "id": "cUiDbO6", "name": "the-black-knight" },
	{ "id": "Xrexxt5", "name": "war-golem" },
	{ "id": "ue6gbY1", "name": "prophet-velen" },
	{ "id": "7kSCZM1", "name": "guardian-of-kings" },
	{ "id": "kaT7p5o", "name": "gahzrilla" },
	{ "id": "eF0y9GC", "name": "archmage-antonidas" },
	{ "id": "awZuLNp", "name": "ancient-of-war" },
	{ "id": "sIqDPC9", "name": "ravenholdt-assassin" },
	{ "id": "fymRC4Z", "name": "stormwind-champion" },
	{ "id": "5dUEUYS", "name": "flame-leviathan" },
	{ "id": "FIarsk3", "name": "flamestrike" },
	{ "id": "8LtoiUL", "name": "core-hound" },
	{ "id": "XKWSSok", "name": "malorne" },
	{ "id": "YPMGNxz", "name": "sprint" },
	{ "id": "uFfh2yr", "name": "ancient-of-lore" },
	{ "id": "IngTCnG", "name": "dr-boom" },
	{ "id": "LeK4WHa", "name": "neptulon" },
	{ "id": "5FMmQq1", "name": "gorehowl" },
	{ "id": "MOluhiu", "name": "gladiators-longbow" },
	{ "id": "2YFulm1", "name": "baron-geddon" },
	{ "id": "MRJtQk3", "name": "crush" },
	{ "id": "5IUqupl", "name": "troggzor-the-earthinator" },
	{ "id": "wKaRNAx", "name": "kelthuzad" },
	{ "id": "otayiPz", "name": "lay-on-hands" },
	{ "id": "BXSLSD6", "name": "ironbark-protector" },
	{ "id": "NYJyQzf", "name": "force-tank-max" },
	{ "id": "cya0lys", "name": "twisting-nether" },
	{ "id": "XinDDsD", "name": "tirion-fordring" },
	{ "id": "wXE4aLN", "name": "sneeds-old-shredder" },
	{ "id": "uPf3wyd", "name": "grommash-hellscream" },
	{ "id": "GQWmoxe", "name": "gruul" },
	{ "id": "8FCoUAk", "name": "foe-reaper-4000" },
	{ "id": "jhq6Hhr", "name": "ragnaros-the-firelord" },
	{ "id": "N2Lo2BD", "name": "alakir-the-windlord" },
	{ "id": "GiriWHg", "name": "ysera" },
	{ "id": "roJ9jrH", "name": "lord-jaraxxus" },
	{ "id": "HlL3Zyy", "name": "cenarius" },
	{ "id": "lTkbIyY", "name": "onyxia" },
	{ "id": "LwXkuLN", "name": "king-krush" },
	{ "id": "OkaL1Ba", "name": "malganis" },
	{ "id": "ZK7BEo3", "name": "malygos" },
	{ "id": "wHTUW2r", "name": "mekgineer-thermaplugg" },
	{ "id": "a9dP0aX", "name": "tree-of-life" },
	{ "id": "JE6r6zk", "name": "nozdormu" },
	{ "id": "iA7yKEA", "name": "alexstrasza" },
	{ "id": "zcGb0hG", "name": "deathwing" },
	{ "id": "I6fr13w", "name": "sea-giant" },
	{ "id": "ialejFb", "name": "pyroblast" },
	{ "id": "NPPA27g", "name": "mind-control" },
	{ "id": "sqBQ6gc", "name": "clockwork-giant" },
	{ "id": "oA7Ae2Q", "name": "mountain-giant" },
	{ "id": "PzNAupY", "name": "molten-giant" },
	{"id":"WZY9H1l","name":"arcane-blast"},
	{"id":"McuKkrx","name":"brave-archer"},
	{"id":"7TscIOi","name":"buccaneer"},
	{"id":"018NPTN","name":"competitive-spirit"},
	{"id":"WkhgbDR","name":"flash-heal"},
	{"id":"WLk2F33","name":"gadgetzan-jouster"},
	{"id":"8QPE7aD","name":"injured-kvaldir"},
	{"id":"Po5rwii","name":"living-roots"},
	{"id":"NcBA4WB","name":"lowly-squire"},
	{"id":"e0mw3t7","name":"power-word-glory"},
	{"id":"1NH53UT","name":"tournament-attendee"},
	{"id":"ofDAWwa","name":"alexstraszas-champion"},
	{"id":"HslKw5t","name":"ancestral-knowledge"},
	{"id":"fSKdGM4","name":"argent-lance"},
	{"id":"8ocIKp8","name":"argent-watchman"},
	{"id":"moyb9iy","name":"bear-trap"},
	{"id":"mGsj4bs","name":"bolster"},
	{"id":"MpaZsn8","name":"boneguard-lieutenant"},
	{"id":"w6n5y3J","name":"confuse"},
	{"id":"0NA4DMq","name":"convert"},
	{"id":"MNnHQHX","name":"cutpurse"},
	{"id":"JEns9oE","name":"darnassus-aspirant"},
	{"id":"b5qaUMa","name":"demonfuse"},
	{"id":"CxTUGPT","name":"druid-of-the-saber"},
	{"id":"jBUsTrb","name":"fallen-hero"},
	{"id":"domZKXu","name":"flame-juggler"},
	{"id":"ND9TlJY","name":"garrison-commander"},
	{"id":"WABHKIN","name":"kings-elekk"},
	{"id":"1gkEjM4","name":"lance-carrier"},
	{"id":"dfuD8N0","name":"lock-and-load"},
	{"id":"cW1aZoF","name":"sparring-partner"},
	{"id":"80waaf2","name":"tiny-knight-of-evil"},
	{"id":"Y29mXYU","name":"totem-golem"},
	{"id":"Ix4G3FF","name":"undercity-valiant"},
	{"id":"tBx9Ddd","name":"wrathguard"},
	{"id":"mRFse2t","name":"wyrmrest-agent"},
	{"id":"wMwAbR0","name":"argent-horserider"},
	{"id":"GZFZiE4","name":"bash"},
	{"id":"AEY8DgX","name":"beneath-the-grounds"},
	{"id":"05NzrI6","name":"burgle"},
	{"id":"eT21kkN","name":"coliseum-manager"},
	{"id":"97JRir9","name":"dragonhawk-rider"},
	{"id":"hC0kHlO","name":"dreadscale"},
	{"id":"MRtOFHP","name":"effigy"},
	{"id":"u1uL7Po","name":"elemental-destruction"},
	{"id":"Pol55MO","name":"eydis-darkbane"},
	{"id":"ewErndj","name":"fencing-coach"},
	{"id":"tzxejtT","name":"fjola-lightbane"},
	{"id":"QteraAG","name":"healing-wave"},
	{"id":"4ZWOEfG","name":"ice-rager"},
	{"id":"35Gn4Wk","name":"kings-defender"},
	{"id":"WAsWdQ6","name":"lights-champion"},
	{"id":"uWOziiR","name":"master-of-ceremonies"},
	{"id":"UW05KhN","name":"mulch"},
	{"id":"z7bHz1S","name":"orgrimmar-aspirant"},
	{"id":"YZdA6lC","name":"polymorph-boar"},
	{"id":"8i6Xb6a","name":"powershot"},
	{"id":"mdmjBBt","name":"saboteur"},
	{"id":"QMPf4YI","name":"seal-of-champions"},
	{"id":"fHQq703","name":"shadowfiend"},
	{"id":"jobg8ti","name":"shady-dealer"},
	{"id":"xNiS8SP","name":"silent-knight"},
	{"id":"Z97PMFK","name":"silver-hand-regent"},
	{"id":"9QrYFuo","name":"spellslinger"},
	{"id":"ZUUxd77","name":"stablemaster"},
	{"id":"xU2hHRd","name":"tuskarr-totemic"},
	{"id":"yXXnOW2","name":"warhorse-trainer"},
	{"id":"NtYDP2T","name":"armored-warhorse"},
	{"id":"OIsHhfe","name":"astral-communion"},
	{"id":"ccSTKFd","name":"charged-hammer"},
	{"id":"57ns5y3","name":"crowd-favorite"},
	{"id":"HiIQJt9","name":"dalaran-aspirant"},
	{"id":"i0Q4rHr","name":"draenei-totemcarver"},
	{"id":"gkj6GF2","name":"dreadsteed"},
	{"id":"5jt93l1","name":"evil-heckler"},
	{"id":"T8x0iHX","name":"fist-of-jaraxxus"},
	{"id":"omwltME","name":"frigid-snobold"},
	{"id":"DFuUJJx","name":"gormok-the-impaler"},
	{"id":"g8XgOe4","name":"holy-champion"},
	{"id":"bxn4rUh","name":"magnataur-alpha"},
	{"id":"GgmFdWn","name":"maiden-of-the-lake"},
	{"id":"oJo6l4b","name":"murloc-knight"},
	{"id":"leBYSPu","name":"poisoned-blade"},
	{"id":"n1J1lyu","name":"refreshment-vendor"},
	{"id":"7fMAbJN","name":"savage-combatant"},
	{"id":"XY7Oxhe","name":"spawn-of-shadows"},
	{"id":"uuK7KKX","name":"tournament-medic"},
	{"id":"02fSHOy","name":"twilight-guardian"},
	{"id":"si68w3c","name":"wildwalker"},
	{"id":"ItDCioh","name":"clockwork-knight"},
	{"id":"MhibOiZ","name":"flame-lance"},
	{"id":"TInM0DA","name":"kvaldir-raider"},
	{"id":"7gqsTMS","name":"muklas-champion"},
	{"id":"pQASlWD","name":"nexus-champion-saraad"},
	{"id":"Fqu9ZzZ","name":"pit-fighter"},
	{"id":"qchLOiR","name":"ram-wrangler"},
	{"id":"fxwbYA5","name":"recruiter"},
	{"id":"8FL8ShS","name":"shado-pan-rider"},
	{"id":"pftN1mU","name":"thunder-bluff-valiant"},
	{"id":"Kumzukf","name":"tuskarr-jouster"},
	{"id":"u9p7bLH","name":"ball-of-spiders"},
	{"id":"TT6PRj8","name":"bolf-ramshield"},
	{"id":"CGQd07q","name":"coldarra-drake"},
	{"id":"amGTl4K","name":"dark-bargain"},
	{"id":"e6dzBIT","name":"enter-the-coliseum"},
	{"id":"x7kKOP3","name":"grand-crusader"},
	{"id":"gzi2W9d","name":"justicar-trueheart"},
	{"id":"j6oSqRk","name":"kodorider"},
	{"id":"1pe0Ehy","name":"master-jouster"},
	{"id":"UBrqIEX","name":"mogors-champion"},
	{"id":"W2tbCI7","name":"mysterious-challenger"},
	{"id":"1EREcJQ","name":"sea-reaver"},
	{"id":"DHe0knI","name":"sideshow-spelleater"},
	{"id":"6ByWBTs","name":"the-mistcaller"},
	{"id":"Uw1kZqK","name":"the-skeleton-knight"},
	{"id":"OcPdKUs","name":"void-crusher"},
	{"id":"eYwgSMg","name":"wilfred-fizzlebang"},
	{"id":"m35AisB","name":"acidmaw"},
	{"id":"aMyjJM2","name":"captured-jormungar"},
	{"id":"ACzzEiX","name":"chillmaw"},
	{"id":"rWcORqJ","name":"confessor-paletress"},
	{"id":"SlSrYfo","name":"eadric-the-pure"},
	{"id":"zIeoAk7","name":"fearsome-doomguard"},
	{"id":"HwbFBO5","name":"knight-of-the-wild"},
	{"id":"XYWauej","name":"skycapn-kragg"},
	{"id":"2IjARSh","name":"rhonin"},
	{"id":"2L7dPy1","name":"anubarak"},
	{"id":"UB1yz9E","name":"aviana"},
	{"id":"MI2lMOF","name":"icehowl"},
	{"id":"0udpsxs","name":"north-sea-kraken"},
	{"id":"9cTxoKj","name":"frost-giant"},
	{"id":"3n8LuYu","name":"varian-wrynn"},
];