/*
 * This file is part of HearthStoneHelper.
 *
 * HearthStoneHelper is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * HearthStoneHelper is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with HearthStoneHelper.  If not, see <http://www.gnu.org/licenses/>.
 */
// ///////////////
// Default / Basic decks for each hero, in JSON format
var jBasicDecks = [
{
  "name": "Garrosh",
  "hero": 1,
  "cards": [{
    "card": "CS2_121",
    "count": 2
  }, {
    "card": "CS2_162",
    "count": 2
  }, {
    "card": "CS2_168",
    "count": 2
  }, {
    "card": "CS2_196",
    "count": 2
  }, {
    "card": "CS2_124",
    "count": 2
  }, {
    "card": "CS2_103",
    "count": 2
  }, {
    "card": "CS2_106",
    "count": 2
  }, {
    "card": "EX1_025",
    "count": 2
  }, {
    "card": "CS2_179",
    "count": 2
  }, {
    "card": "EX1_399",
    "count": 2
  }, {
    "card": "CS2_108",
    "count": 2
  }, {
    "card": "EX1_506",
    "count": 2
  }, {
    "card": "CS2_105",
    "count": 2
  }, {
    "card": "EX1_084",
    "count": 2
  }, {
    "card": "CS2_200",
    "count": 2
  }],
  "isarena": false
}, {
  "name": "Uther",
  "hero": 2,
  "cards": [{
    "card": "CS2_087",
    "count": 2
  }, {
    "card": "CS2_162",
    "count": 2
  }, {
    "card": "CS2_094",
    "count": 2
  }, {
    "card": "EX1_015",
    "count": 2
  }, {
    "card": "CS2_089",
    "count": 2
  }, {
    "card": "CS2_147",
    "count": 2
  }, {
    "card": "CS2_141",
    "count": 2
  }, {
    "card": "CS2_091",
    "count": 2
  }, {
    "card": "CS2_189",
    "count": 2
  }, {
    "card": "CS2_150",
    "count": 2
  }, {
    "card": "CS2_131",
    "count": 2
  }, {
    "card": "EX1_371",
    "count": 2
  }, {
    "card": "CS2_222",
    "count": 2
  }, {
    "card": "CS1_042",
    "count": 2
  }, {
    "card": "CS2_122",
    "count": 2
  }],
  "isarena": false
}, {
  "name": "Rexxar",
  "hero": 3,
  "cards": [{
    "card": "CS2_172",
    "count": 2
  }, {
    "card": "CS2_196",
    "count": 2
  }, {
    "card": "EX1_015",
    "count": 2
  }, {
    "card": "DS1_183",
    "count": 2
  }, {
    "card": "DS1_175",
    "count": 2
  }, {
    "card": "CS2_171",
    "count": 2
  }, {
    "card": "DS1_185",
    "count": 2
  }, {
    "card": "CS1_042",
    "count": 2
  }, {
    "card": "DS1_070",
    "count": 2
  }, {
    "card": "DS1_184",
    "count": 2
  }, {
    "card": "CS2_125",
    "count": 2
  }, {
    "card": "CS2_120",
    "count": 2
  }, {
    "card": "CS2_119",
    "count": 2
  }, {
    "card": "CS2_122",
    "count": 2
  }, {
    "card": "CS2_201",
    "count": 2
  }],
  "isarena": false
}, {
  "name": "Valeera",
  "hero": 4,
  "cards": [{
    "card": "CS2_072",
    "count": 2
  }, {
    "card": "CS2_172",
    "count": 2
  }, {
    "card": "EX1_015",
    "count": 2
  }, {
    "card": "CS2_147",
    "count": 2
  }, {
    "card": "CS2_141",
    "count": 2
  }, {
    "card": "CS2_076",
    "count": 2
  }, {
    "card": "CS2_189",
    "count": 2
  }, {
    "card": "CS2_150",
    "count": 2
  }, {
    "card": "CS2_074",
    "count": 2
  }, {
    "card": "EX1_581",
    "count": 2
  }, {
    "card": "EX1_025",
    "count": 2
  }, {
    "card": "CS2_131",
    "count": 2
  }, {
    "card": "EX1_593",
    "count": 2
  }, {
    "card": "CS2_075",
    "count": 2
  }, {
    "card": "CS1_042",
    "count": 2
  }],
  "isarena": false
}, {
  "name": "Thrall",
  "hero": 7,
  "cards": [{
    "card": "CS2_121",
    "count": 2
  }, {
    "card": "CS2_039",
    "count": 2
  }, {
    "card": "EX1_011",
    "count": 2
  }, {
    "card": "CS2_041",
    "count": 2
  }, {
    "card": "CS2_168",
    "count": 2
  }, {
    "card": "CS2_045",
    "count": 2
  }, {
    "card": "CS2_124",
    "count": 2
  }, {
    "card": "CS2_213",
    "count": 2
  }, {
    "card": "CS2_226",
    "count": 2
  }, {
    "card": "CS2_179",
    "count": 2
  }, {
    "card": "CS2_171",
    "count": 2
  }, {
    "card": "EX1_246",
    "count": 2
  }, {
    "card": "CS2_037",
    "count": 2
  }, {
    "card": "CS2_187",
    "count": 2
  }, {
    "card": "CS2_122",
    "count": 2
  }],
  "isarena": false
}, {
  "name": "Jaina",
  "hero": 8,
  "cards": [{
    "card": "CS2_022",
    "count": 2
  }, {
    "card": "CS2_168",
    "count": 2
  }, {
    "card": "CS2_172",
    "count": 2
  }, {
    "card": "EX1_015",
    "count": 2
  }, {
    "card": "CS2_124",
    "count": 2
  }, {
    "card": "CS2_029",
    "count": 2
  }, {
    "card": "CS2_025",
    "count": 2
  }, {
    "card": "CS2_023",
    "count": 2
  }, {
    "card": "EX1_277",
    "count": 2
  }, {
    "card": "CS2_179",
    "count": 2
  }, {
    "card": "EX1_593",
    "count": 2
  }, {
    "card": "CS2_120",
    "count": 2
  }, {
    "card": "CS2_119",
    "count": 2
  }, {
    "card": "CS2_122",
    "count": 2
  }, {
    "card": "CS2_200",
    "count": 2
  }],
  "isarena": false
}, {
  "name": "Gul'dan",
  "hero": 9,
  "cards": [{
    "card": "CS2_065",
    "count": 2
  }, {
    "card": "CS2_182",
    "count": 2
  }, {
    "card": "EX1_011",
    "count": 2
  }, {
    "card": "CS2_168",
    "count": 2
  }, {
    "card": "CS2_124",
    "count": 2
  }, {
    "card": "CS2_213",
    "count": 2
  }, {
    "card": "DS1_055",
    "count": 2
  }, {
    "card": "EX1_306",
    "count": 2
  }, {
    "card": "CS2_142",
    "count": 2
  }, {
    "card": "CS2_186",
    "count": 2
  }, {
    "card": "CS2_057",
    "count": 2
  }, {
    "card": "CS2_061",
    "count": 2
  }, {
    "card": "CS2_062",
    "count": 2
  }, {
    "card": "CS2_197",
    "count": 2
  }, {
    "card": "CS2_120",
    "count": 2
  }],
  "isarena": false
}, {
  "name": "Malfurion",
  "hero": 11,
  "cards": [{
    "card": "CS2_127",
    "count": 2
  }, {
    "card": "CS2_162",
    "count": 2
  }, {
    "card": "CS2_009",
    "count": 2
  }, {
    "card": "CS2_172",
    "count": 2
  }, {
    "card": "EX1_169",
    "count": 2
  }, {
    "card": "CS2_189",
    "count": 2
  }, {
    "card": "CS2_171",
    "count": 2
  }, {
    "card": "EX1_593",
    "count": 2
  }, {
    "card": "CS2_007",
    "count": 2
  }, {
    "card": "CS2_005",
    "count": 2
  }, {
    "card": "CS2_013",
    "count": 2
  }, {
    "card": "CS2_120",
    "count": 2
  }, {
    "card": "CS2_119",
    "count": 2
  }, {
    "card": "CS2_200",
    "count": 2
  }, {
    "card": "CS2_201",
    "count": 2
  }],
  "isarena": false
}, {
  "name": "Anduin",
  "hero": 5,
  "cards": [{
    "card": "CS2_121",
    "count": 2
  }, {
    "card": "CS2_127",
    "count": 2
  }, {
    "card": "CS2_182",
    "count": 2
  }, {
    "card": "EX1_011",
    "count": 2
  }, {
    "card": "CS2_172",
    "count": 2
  }, {
    "card": "CS1_130",
    "count": 2
  }, {
    "card": "CS2_189",
    "count": 2
  }, {
    "card": "DS1_233",
    "count": 2
  }, {
    "card": "EX1_019",
    "count": 2
  }, {
    "card": "CS2_004",
    "count": 2
  }, {
    "card": "CS2_179",
    "count": 2
  }, {
    "card": "EX1_399",
    "count": 2
  }, {
    "card": "CS2_234",
    "count": 2
  }, {
    "card": "CS2_235",
    "count": 2
  }, {
    "card": "CS2_201",
    "count": 2
  }],
  "isarena": false
}];